---
title: "Bayes BATS Tier 2 Schedule"
title-block-banner: true
format:
  html:
    toc: true
    toc-title: "Content"
    toc-location: left
    html-math-method: katex
    theme: 
      -  style.scss
    page-layout: full
---

```{r}
#| echo: false

library(fontawesome)
```

## Office Hours

Regardless of whether you are admitted to Tier 2 or not, if you have participated in Tier 1, you are welcome to attend office hours. Each PI will have one office hour each month. You can meet any PI, not necessarily the one assigned to your group. More details will be added.

| Date       | Time               | PI     | Zoom Link |
|------------|--------------------|--------|-----------|
| 2024-09-06 | 3:00 - 4:00 pm ET      | Amy | [`r fontawesome::fa(name = "video")`](https://duke.zoom.us/my/amyherring?pwd=UWczUjFOOXZ2MlhuYTMrLzVka05sQT09) password 11111         |
| 2024-09-18 | 3:30 - 4:30 pm ET | Monika |  [`r fontawesome::fa(name = "video")`](https://vassar.zoom.us/my/monika76five)        |
| 2024-09-26 | 12:00 - 1:00 pm ET  | Mine    |[`r fontawesome::fa(name = "video")`](https://uci.zoom.us/j/91799232149)          |
| 2024-10-07 | 3:30 - 4:30 pm ET | Monika |  [`r fontawesome::fa(name = "video")`](https://vassar.zoom.us/my/monika76five)        |
| 2024-10-15 | 3:00 - 4:00 pm ET      | Amy |     [`r fontawesome::fa(name = "video")`](https://duke.zoom.us/my/amyherring?pwd=UWczUjFOOXZ2MlhuYTMrLzVka05sQT09) password 11111     |
| 2024-10-22 | 4:00 - 5:00 pm ET | Mine |[`r fontawesome::fa(name = "video")`](https://uci.zoom.us/j/93009936370) |
| 2024-11-07 |2:00 - 3:00 pm ET | Mine |[`r fontawesome::fa(name = "video")`](https://uci.zoom.us/j/96570454362) |
| 2024-11-12 | 3:00 - 4:00 pm ET      | Amy |   [`r fontawesome::fa(name = "video")`](https://duke.zoom.us/my/amyherring?pwd=UWczUjFOOXZ2MlhuYTMrLzVka05sQT09) password 11111       |
| 2023-11-20 | 3:30 - 4:30 pm ET | Monika |  [`r fontawesome::fa(name = "video")`](https://vassar.zoom.us/my/monika76five)        |


## Timeline

Each Tier 2 group will meet with their assigned mentor once a month to discuss the progress of the projects. Below is the expected timeline for all groups. 

| Date                | Item                                                                     |
|---------------------|--------------------------------------------------------------------------|
| Friday September 6th, 2024 | Submission of detailed work plan (goals, timeline, etc.)                 |
| Friday October 4th, 2024   | Submission of progress report 1                                                   |
| Friday November 1st, 2024  | Submission of progress report 2                                                   |
| Friday December 6th, 2024  | Submission of materials (including a 5- or 10-minute video presentation) |
